//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIntegration.MailService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://ddse.redmond.corp.microsoft.com/GoFxServMailer/", ConfigurationName="MailService.GoFxServMailerSoap")]
    public interface GoFxServMailerSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ddse.redmond.corp.microsoft.com/GoFxServMailer/Test_SendEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Test_SendEmail();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ddse.redmond.corp.microsoft.com/GoFxServMailer/Test_SendEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> Test_SendEmailAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ddse.redmond.corp.microsoft.com/GoFxServMailer/SendErrorMail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SendErrorMail(string exceptionMsg, string subject, string customMsg, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ddse.redmond.corp.microsoft.com/GoFxServMailer/SendErrorMail", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SendErrorMailAsync(string exceptionMsg, string subject, string customMsg, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ddse.redmond.corp.microsoft.com/GoFxServMailer/SendMail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SendMail(string subject, string body, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ddse.redmond.corp.microsoft.com/GoFxServMailer/SendMail", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SendMailAsync(string subject, string body, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ddse.redmond.corp.microsoft.com/GoFxServMailer/SendEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SendEmail(string[] toList, string[] ccList, string subject, string body);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ddse.redmond.corp.microsoft.com/GoFxServMailer/SendEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SendEmailAsync(string[] toList, string[] ccList, string subject, string body);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ddse.redmond.corp.microsoft.com/GoFxServMailer/SendEmailwAtt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SendEmailwAtt(string[] toList, string[] ccList, string subject, string body, string[] attachments);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ddse.redmond.corp.microsoft.com/GoFxServMailer/SendEmailwAtt", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SendEmailwAttAsync(string[] toList, string[] ccList, string subject, string body, string[] attachments);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GoFxServMailerSoapChannel : RMIntegration.MailService.GoFxServMailerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GoFxServMailerSoapClient : System.ServiceModel.ClientBase<RMIntegration.MailService.GoFxServMailerSoap>, RMIntegration.MailService.GoFxServMailerSoap {
        
        public GoFxServMailerSoapClient() {
        }
        
        public GoFxServMailerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GoFxServMailerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GoFxServMailerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GoFxServMailerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Test_SendEmail() {
            return base.Channel.Test_SendEmail();
        }
        
        public System.Threading.Tasks.Task<bool> Test_SendEmailAsync() {
            return base.Channel.Test_SendEmailAsync();
        }
        
        public bool SendErrorMail(string exceptionMsg, string subject, string customMsg, string userName) {
            return base.Channel.SendErrorMail(exceptionMsg, subject, customMsg, userName);
        }
        
        public System.Threading.Tasks.Task<bool> SendErrorMailAsync(string exceptionMsg, string subject, string customMsg, string userName) {
            return base.Channel.SendErrorMailAsync(exceptionMsg, subject, customMsg, userName);
        }
        
        public bool SendMail(string subject, string body, string userName) {
            return base.Channel.SendMail(subject, body, userName);
        }
        
        public System.Threading.Tasks.Task<bool> SendMailAsync(string subject, string body, string userName) {
            return base.Channel.SendMailAsync(subject, body, userName);
        }
        
        public bool SendEmail(string[] toList, string[] ccList, string subject, string body) {
            return base.Channel.SendEmail(toList, ccList, subject, body);
        }
        
        public System.Threading.Tasks.Task<bool> SendEmailAsync(string[] toList, string[] ccList, string subject, string body) {
            return base.Channel.SendEmailAsync(toList, ccList, subject, body);
        }
        
        public bool SendEmailwAtt(string[] toList, string[] ccList, string subject, string body, string[] attachments) {
            return base.Channel.SendEmailwAtt(toList, ccList, subject, body, attachments);
        }
        
        public System.Threading.Tasks.Task<bool> SendEmailwAttAsync(string[] toList, string[] ccList, string subject, string body, string[] attachments) {
            return base.Channel.SendEmailwAttAsync(toList, ccList, subject, body, attachments);
        }
    }
}
