//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 

namespace Microsoft.UpdateServices.Publishing.Schemas
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class PublishingQueryResult
    {

        private PublishingQueryResultUpdate[] updateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Update")]
        public PublishingQueryResultUpdate[] Update
        {
            get
            {
                return this.updateField;
            }
            set
            {
                this.updateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class PublishingQueryResultUpdate
    {

        private string updateIDField;

        private string updateTypeField;

        private bool isLocalField;

        private string titleField;

        private bool isLeafField;

        private bool isPublicField;

        private bool isSupersededField;

        private string stateField;

        private string roqStateField;

        private bool excludedByDefaultField;

        private bool consumerOnlyField;

        private bool isPrivateField;

        private bool isSearchableField;

        private bool disabledField;

        private string revisionNumberField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UpdateID
        {
            get
            {
                return this.updateIDField;
            }
            set
            {
                this.updateIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UpdateType
        {
            get
            {
                return this.updateTypeField;
            }
            set
            {
                this.updateTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsLocal
        {
            get
            {
                return this.isLocalField;
            }
            set
            {
                this.isLocalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsLeaf
        {
            get
            {
                return this.isLeafField;
            }
            set
            {
                this.isLeafField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsPublic
        {
            get
            {
                return this.isPublicField;
            }
            set
            {
                this.isPublicField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsSuperseded
        {
            get
            {
                return this.isSupersededField;
            }
            set
            {
                this.isSupersededField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RoqState
        {
            get
            {
                return this.roqStateField;
            }
            set
            {
                this.roqStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ExcludedByDefault
        {
            get
            {
                return this.excludedByDefaultField;
            }
            set
            {
                this.excludedByDefaultField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ConsumerOnly
        {
            get
            {
                return this.consumerOnlyField;
            }
            set
            {
                this.consumerOnlyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsPrivate
        {
            get
            {
                return this.isPrivateField;
            }
            set
            {
                this.isPrivateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsSearchable
        {
            get
            {
                return this.isSearchableField;
            }
            set
            {
                this.isSearchableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Disabled
        {
            get
            {
                return this.disabledField;
            }
            set
            {
                this.disabledField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RevisionNumber
        {
            get
            {
                return this.revisionNumberField;
            }
            set
            {
                this.revisionNumberField = value;
            }
        }
    }

    // update types to query the Pubsuite for
    public enum PubsuiteUpdateType
    {
        Bundle,
        HotfixBundle,
        BundleCategoryDetectoid
    };
}