//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WUTestManagerLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ivwApiUpdateRevision
    {
        public System.Guid UpdateID { get; set; }
        public int RevisionNumber { get; set; }
        public int LocalUpdateID { get; set; }
        public int RevisionID { get; set; }
        public bool IsLatestRevision { get; set; }
        public bool IsHidden { get; set; }
        public string UpdateType { get; set; }
        public bool IsLocallyPublished { get; set; }
        public Nullable<int> DefaultPropertiesLanguageID { get; set; }
        public bool IsMandatory { get; set; }
        public System.DateTime EffectiveArrivalTime { get; set; }
    }
}
