//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WUTestManagerLib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SUSDBEntities : DbContext
    {
        public SUSDBEntities()
            : base("name=SUSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbKBArticleForRevision> tbKBArticleForRevisions { get; set; }
        public virtual DbSet<tbRevisionSupersedesUpdate> tbRevisionSupersedesUpdates { get; set; }
        public virtual DbSet<tbUpdateMetaData> tbUpdateMetaDatas { get; set; }
        public virtual DbSet<ivwApiUpdateRevision> ivwApiUpdateRevisions { get; set; }
    }
}
