//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WUTestManagerLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRevisionSupersedesUpdate
    {
        public int RevisionID { get; set; }
        public System.Guid SupersededUpdateID { get; set; }
    }
}
