//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WUTestManagerLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUpdateMetaData
    {
        public System.Guid PackageId { get; set; }
        public int RevisionNumber { get; set; }
        public string PackageTitle { get; set; }
        public Nullable<System.Guid> PublisherId { get; set; }
        public Nullable<bool> RequiresReboot { get; set; }
        public Nullable<bool> IsBeta { get; set; }
        public Nullable<bool> IsExpired { get; set; }
        public Nullable<bool> IsDriver { get; set; }
        public Nullable<bool> IsAssigned { get; set; }
        public Nullable<bool> MarkedAsASOWS { get; set; }
    }
}
