//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMIntegration.RMService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Release", Namespace="http://schemas.datacontract.org/2004/07/ReleaseManService.Model")]
    [System.SerializableAttribute()]
    public partial class Release : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDualBranchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MTPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RMIntegration.RMService.Patch[] PatchesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreMTPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReleaseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReleaseTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityVulnerabilityTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ShipDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDualBranch {
            get {
                return this.IsDualBranchField;
            }
            set {
                if ((this.IsDualBranchField.Equals(value) != true)) {
                    this.IsDualBranchField = value;
                    this.RaisePropertyChanged("IsDualBranch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MTP {
            get {
                return this.MTPField;
            }
            set {
                if ((object.ReferenceEquals(this.MTPField, value) != true)) {
                    this.MTPField = value;
                    this.RaisePropertyChanged("MTP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Owner {
            get {
                return this.OwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerField, value) != true)) {
                    this.OwnerField = value;
                    this.RaisePropertyChanged("Owner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RMIntegration.RMService.Patch[] Patches {
            get {
                return this.PatchesField;
            }
            set {
                if ((object.ReferenceEquals(this.PatchesField, value) != true)) {
                    this.PatchesField = value;
                    this.RaisePropertyChanged("Patches");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreMTP {
            get {
                return this.PreMTPField;
            }
            set {
                if ((object.ReferenceEquals(this.PreMTPField, value) != true)) {
                    this.PreMTPField = value;
                    this.RaisePropertyChanged("PreMTP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReleaseId {
            get {
                return this.ReleaseIdField;
            }
            set {
                if ((this.ReleaseIdField.Equals(value) != true)) {
                    this.ReleaseIdField = value;
                    this.RaisePropertyChanged("ReleaseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReleaseType {
            get {
                return this.ReleaseTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReleaseTypeField, value) != true)) {
                    this.ReleaseTypeField = value;
                    this.RaisePropertyChanged("ReleaseType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityVulnerabilityType {
            get {
                return this.SecurityVulnerabilityTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityVulnerabilityTypeField, value) != true)) {
                    this.SecurityVulnerabilityTypeField = value;
                    this.RaisePropertyChanged("SecurityVulnerabilityType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ShipDate {
            get {
                return this.ShipDateField;
            }
            set {
                if ((this.ShipDateField.Equals(value) != true)) {
                    this.ShipDateField = value;
                    this.RaisePropertyChanged("ShipDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Patch", Namespace="http://schemas.datacontract.org/2004/07/ReleaseManService.Model")]
    [System.SerializableAttribute()]
    public partial class Patch : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RMIntegration.RMService.Change[] ChangesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpectedFilesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RMIntegration.RMService.File[] FilesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDualBranchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> KBNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RMIntegration.RMService.PatchMetaData MetaDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatchBuildGDRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatchBuildLDRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatchLocationARMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatchLocationARM64Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatchLocationIA64Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatchLocationx64Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatchLocationx86Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatchNameARMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatchNameARM64Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatchNameIA64Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatchNamex64Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatchNamex86Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReleaseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReleaseTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ShippingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceBuildGDRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceBuildLDRField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RMIntegration.RMService.Change[] Changes {
            get {
                return this.ChangesField;
            }
            set {
                if ((object.ReferenceEquals(this.ChangesField, value) != true)) {
                    this.ChangesField = value;
                    this.RaisePropertyChanged("Changes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpectedFiles {
            get {
                return this.ExpectedFilesField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpectedFilesField, value) != true)) {
                    this.ExpectedFilesField = value;
                    this.RaisePropertyChanged("ExpectedFiles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RMIntegration.RMService.File[] Files {
            get {
                return this.FilesField;
            }
            set {
                if ((object.ReferenceEquals(this.FilesField, value) != true)) {
                    this.FilesField = value;
                    this.RaisePropertyChanged("Files");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDualBranch {
            get {
                return this.IsDualBranchField;
            }
            set {
                if ((this.IsDualBranchField.Equals(value) != true)) {
                    this.IsDualBranchField = value;
                    this.RaisePropertyChanged("IsDualBranch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> KBNumber {
            get {
                return this.KBNumberField;
            }
            set {
                if ((this.KBNumberField.Equals(value) != true)) {
                    this.KBNumberField = value;
                    this.RaisePropertyChanged("KBNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RMIntegration.RMService.PatchMetaData MetaData {
            get {
                return this.MetaDataField;
            }
            set {
                if ((object.ReferenceEquals(this.MetaDataField, value) != true)) {
                    this.MetaDataField = value;
                    this.RaisePropertyChanged("MetaData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatchBuildGDR {
            get {
                return this.PatchBuildGDRField;
            }
            set {
                if ((object.ReferenceEquals(this.PatchBuildGDRField, value) != true)) {
                    this.PatchBuildGDRField = value;
                    this.RaisePropertyChanged("PatchBuildGDR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatchBuildLDR {
            get {
                return this.PatchBuildLDRField;
            }
            set {
                if ((object.ReferenceEquals(this.PatchBuildLDRField, value) != true)) {
                    this.PatchBuildLDRField = value;
                    this.RaisePropertyChanged("PatchBuildLDR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatchLocationARM {
            get {
                return this.PatchLocationARMField;
            }
            set {
                if ((object.ReferenceEquals(this.PatchLocationARMField, value) != true)) {
                    this.PatchLocationARMField = value;
                    this.RaisePropertyChanged("PatchLocationARM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatchLocationARM64 {
            get {
                return this.PatchLocationARM64Field;
            }
            set {
                if ((object.ReferenceEquals(this.PatchLocationARM64Field, value) != true)) {
                    this.PatchLocationARM64Field = value;
                    this.RaisePropertyChanged("PatchLocationARM64");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatchLocationIA64 {
            get {
                return this.PatchLocationIA64Field;
            }
            set {
                if ((object.ReferenceEquals(this.PatchLocationIA64Field, value) != true)) {
                    this.PatchLocationIA64Field = value;
                    this.RaisePropertyChanged("PatchLocationIA64");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatchLocationx64 {
            get {
                return this.PatchLocationx64Field;
            }
            set {
                if ((object.ReferenceEquals(this.PatchLocationx64Field, value) != true)) {
                    this.PatchLocationx64Field = value;
                    this.RaisePropertyChanged("PatchLocationx64");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatchLocationx86 {
            get {
                return this.PatchLocationx86Field;
            }
            set {
                if ((object.ReferenceEquals(this.PatchLocationx86Field, value) != true)) {
                    this.PatchLocationx86Field = value;
                    this.RaisePropertyChanged("PatchLocationx86");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatchNameARM {
            get {
                return this.PatchNameARMField;
            }
            set {
                if ((object.ReferenceEquals(this.PatchNameARMField, value) != true)) {
                    this.PatchNameARMField = value;
                    this.RaisePropertyChanged("PatchNameARM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatchNameARM64 {
            get {
                return this.PatchNameARM64Field;
            }
            set {
                if ((object.ReferenceEquals(this.PatchNameARM64Field, value) != true)) {
                    this.PatchNameARM64Field = value;
                    this.RaisePropertyChanged("PatchNameARM64");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatchNameIA64 {
            get {
                return this.PatchNameIA64Field;
            }
            set {
                if ((object.ReferenceEquals(this.PatchNameIA64Field, value) != true)) {
                    this.PatchNameIA64Field = value;
                    this.RaisePropertyChanged("PatchNameIA64");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatchNamex64 {
            get {
                return this.PatchNamex64Field;
            }
            set {
                if ((object.ReferenceEquals(this.PatchNamex64Field, value) != true)) {
                    this.PatchNamex64Field = value;
                    this.RaisePropertyChanged("PatchNamex64");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatchNamex86 {
            get {
                return this.PatchNamex86Field;
            }
            set {
                if ((object.ReferenceEquals(this.PatchNamex86Field, value) != true)) {
                    this.PatchNamex86Field = value;
                    this.RaisePropertyChanged("PatchNamex86");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReleaseId {
            get {
                return this.ReleaseIdField;
            }
            set {
                if ((this.ReleaseIdField.Equals(value) != true)) {
                    this.ReleaseIdField = value;
                    this.RaisePropertyChanged("ReleaseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReleaseType {
            get {
                return this.ReleaseTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReleaseTypeField, value) != true)) {
                    this.ReleaseTypeField = value;
                    this.RaisePropertyChanged("ReleaseType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Shipping {
            get {
                return this.ShippingField;
            }
            set {
                if ((this.ShippingField.Equals(value) != true)) {
                    this.ShippingField = value;
                    this.RaisePropertyChanged("Shipping");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceBuildGDR {
            get {
                return this.SourceBuildGDRField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceBuildGDRField, value) != true)) {
                    this.SourceBuildGDRField = value;
                    this.RaisePropertyChanged("SourceBuildGDR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceBuildLDR {
            get {
                return this.SourceBuildLDRField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceBuildLDRField, value) != true)) {
                    this.SourceBuildLDRField = value;
                    this.RaisePropertyChanged("SourceBuildLDR");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatchMetaData", Namespace="http://schemas.datacontract.org/2004/07/ReleaseManService.Model")]
    [System.SerializableAttribute()]
    public partial class PatchMetaData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsNetLCUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsNetOnlyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsParentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsWSDLCUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatchDetectionRegKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatchTechnologyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReleaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RMIntegration.RMService.Language[] TargetLanguagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RMIntegration.RMService.OS[] TargetOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WorkitemIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsNetLCU {
            get {
                return this.IsNetLCUField;
            }
            set {
                if ((this.IsNetLCUField.Equals(value) != true)) {
                    this.IsNetLCUField = value;
                    this.RaisePropertyChanged("IsNetLCU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsNetOnly {
            get {
                return this.IsNetOnlyField;
            }
            set {
                if ((this.IsNetOnlyField.Equals(value) != true)) {
                    this.IsNetOnlyField = value;
                    this.RaisePropertyChanged("IsNetOnly");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsParent {
            get {
                return this.IsParentField;
            }
            set {
                if ((this.IsParentField.Equals(value) != true)) {
                    this.IsParentField = value;
                    this.RaisePropertyChanged("IsParent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsWSDLCU {
            get {
                return this.IsWSDLCUField;
            }
            set {
                if ((this.IsWSDLCUField.Equals(value) != true)) {
                    this.IsWSDLCUField = value;
                    this.RaisePropertyChanged("IsWSDLCU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatchDetectionRegKey {
            get {
                return this.PatchDetectionRegKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PatchDetectionRegKeyField, value) != true)) {
                    this.PatchDetectionRegKeyField = value;
                    this.RaisePropertyChanged("PatchDetectionRegKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatchTechnology {
            get {
                return this.PatchTechnologyField;
            }
            set {
                if ((object.ReferenceEquals(this.PatchTechnologyField, value) != true)) {
                    this.PatchTechnologyField = value;
                    this.RaisePropertyChanged("PatchTechnology");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Release {
            get {
                return this.ReleaseField;
            }
            set {
                if ((object.ReferenceEquals(this.ReleaseField, value) != true)) {
                    this.ReleaseField = value;
                    this.RaisePropertyChanged("Release");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RMIntegration.RMService.Language[] TargetLanguages {
            get {
                return this.TargetLanguagesField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetLanguagesField, value) != true)) {
                    this.TargetLanguagesField = value;
                    this.RaisePropertyChanged("TargetLanguages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RMIntegration.RMService.OS[] TargetOS {
            get {
                return this.TargetOSField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetOSField, value) != true)) {
                    this.TargetOSField = value;
                    this.RaisePropertyChanged("TargetOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetProduct {
            get {
                return this.TargetProductField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetProductField, value) != true)) {
                    this.TargetProductField = value;
                    this.RaisePropertyChanged("TargetProduct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WorkitemId {
            get {
                return this.WorkitemIdField;
            }
            set {
                if ((this.WorkitemIdField.Equals(value) != true)) {
                    this.WorkitemIdField = value;
                    this.RaisePropertyChanged("WorkitemId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Change", Namespace="http://schemas.datacontract.org/2004/07/ReleaseManService.Model")]
    [System.SerializableAttribute()]
    public partial class Change : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BinariesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BugNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Binaries {
            get {
                return this.BinariesField;
            }
            set {
                if ((object.ReferenceEquals(this.BinariesField, value) != true)) {
                    this.BinariesField = value;
                    this.RaisePropertyChanged("Binaries");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BugNumber {
            get {
                return this.BugNumberField;
            }
            set {
                if ((this.BugNumberField.Equals(value) != true)) {
                    this.BugNumberField = value;
                    this.RaisePropertyChanged("BugNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Team {
            get {
                return this.TeamField;
            }
            set {
                if ((object.ReferenceEquals(this.TeamField, value) != true)) {
                    this.TeamField = value;
                    this.RaisePropertyChanged("Team");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="File", Namespace="http://schemas.datacontract.org/2004/07/ReleaseManService.Model")]
    [System.SerializableAttribute()]
    public partial class File : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FileDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FileIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileLocaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FileSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FileTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLDRPayloadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSymbolUploadedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatchArchitectureField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FileDate {
            get {
                return this.FileDateField;
            }
            set {
                if ((this.FileDateField.Equals(value) != true)) {
                    this.FileDateField = value;
                    this.RaisePropertyChanged("FileDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FileId {
            get {
                return this.FileIdField;
            }
            set {
                if ((this.FileIdField.Equals(value) != true)) {
                    this.FileIdField = value;
                    this.RaisePropertyChanged("FileId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileLocale {
            get {
                return this.FileLocaleField;
            }
            set {
                if ((object.ReferenceEquals(this.FileLocaleField, value) != true)) {
                    this.FileLocaleField = value;
                    this.RaisePropertyChanged("FileLocale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long FileSize {
            get {
                return this.FileSizeField;
            }
            set {
                if ((this.FileSizeField.Equals(value) != true)) {
                    this.FileSizeField = value;
                    this.RaisePropertyChanged("FileSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FileTime {
            get {
                return this.FileTimeField;
            }
            set {
                if ((this.FileTimeField.Equals(value) != true)) {
                    this.FileTimeField = value;
                    this.RaisePropertyChanged("FileTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileVersion {
            get {
                return this.FileVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.FileVersionField, value) != true)) {
                    this.FileVersionField = value;
                    this.RaisePropertyChanged("FileVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLDRPayload {
            get {
                return this.IsLDRPayloadField;
            }
            set {
                if ((this.IsLDRPayloadField.Equals(value) != true)) {
                    this.IsLDRPayloadField = value;
                    this.RaisePropertyChanged("IsLDRPayload");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSymbolUploaded {
            get {
                return this.IsSymbolUploadedField;
            }
            set {
                if ((this.IsSymbolUploadedField.Equals(value) != true)) {
                    this.IsSymbolUploadedField = value;
                    this.RaisePropertyChanged("IsSymbolUploaded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatchArchitecture {
            get {
                return this.PatchArchitectureField;
            }
            set {
                if ((object.ReferenceEquals(this.PatchArchitectureField, value) != true)) {
                    this.PatchArchitectureField = value;
                    this.RaisePropertyChanged("PatchArchitecture");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Language", Namespace="http://schemas.datacontract.org/2004/07/ReleaseManService.Model")]
    [System.SerializableAttribute()]
    public partial class Language : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryLocaleStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LCIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageShortStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryLocaleString {
            get {
                return this.CountryLocaleStringField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryLocaleStringField, value) != true)) {
                    this.CountryLocaleStringField = value;
                    this.RaisePropertyChanged("CountryLocaleString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LCID {
            get {
                return this.LCIDField;
            }
            set {
                if ((this.LCIDField.Equals(value) != true)) {
                    this.LCIDField = value;
                    this.RaisePropertyChanged("LCID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LanguageShortString {
            get {
                return this.LanguageShortStringField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageShortStringField, value) != true)) {
                    this.LanguageShortStringField = value;
                    this.RaisePropertyChanged("LanguageShortString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OS", Namespace="http://schemas.datacontract.org/2004/07/ReleaseManService.Model")]
    [System.SerializableAttribute()]
    public partial class OS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OSNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OSShortNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalName {
            get {
                return this.ExternalNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalNameField, value) != true)) {
                    this.ExternalNameField = value;
                    this.RaisePropertyChanged("ExternalName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OSName {
            get {
                return this.OSNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OSNameField, value) != true)) {
                    this.OSNameField = value;
                    this.RaisePropertyChanged("OSName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OSShortName {
            get {
                return this.OSShortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OSShortNameField, value) != true)) {
                    this.OSShortNameField = value;
                    this.RaisePropertyChanged("OSShortName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Branch", Namespace="http://schemas.datacontract.org/2004/07/ReleaseManService.Model")]
    [System.SerializableAttribute()]
    public partial class Branch : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BranchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepotPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropertiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TFSSourceControlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BranchId {
            get {
                return this.BranchIdField;
            }
            set {
                if ((this.BranchIdField.Equals(value) != true)) {
                    this.BranchIdField = value;
                    this.RaisePropertyChanged("BranchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepotPath {
            get {
                return this.DepotPathField;
            }
            set {
                if ((object.ReferenceEquals(this.DepotPathField, value) != true)) {
                    this.DepotPathField = value;
                    this.RaisePropertyChanged("DepotPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lab {
            get {
                return this.LabField;
            }
            set {
                if ((object.ReferenceEquals(this.LabField, value) != true)) {
                    this.LabField = value;
                    this.RaisePropertyChanged("Lab");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Properties {
            get {
                return this.PropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertiesField, value) != true)) {
                    this.PropertiesField = value;
                    this.RaisePropertyChanged("Properties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TFSSourceControl {
            get {
                return this.TFSSourceControlField;
            }
            set {
                if ((this.TFSSourceControlField.Equals(value) != true)) {
                    this.TFSSourceControlField = value;
                    this.RaisePropertyChanged("TFSSourceControl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReleaseType", Namespace="http://schemas.datacontract.org/2004/07/ReleaseManService.Model")]
    [System.SerializableAttribute()]
    public partial class ReleaseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDualBranchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReleaseTypeIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDualBranch {
            get {
                return this.IsDualBranchField;
            }
            set {
                if ((this.IsDualBranchField.Equals(value) != true)) {
                    this.IsDualBranchField = value;
                    this.RaisePropertyChanged("IsDualBranch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReleaseTypeId {
            get {
                return this.ReleaseTypeIdField;
            }
            set {
                if ((this.ReleaseTypeIdField.Equals(value) != true)) {
                    this.ReleaseTypeIdField = value;
                    this.RaisePropertyChanged("ReleaseTypeId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/ReleaseManService.Model")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalName {
            get {
                return this.ExternalNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalNameField, value) != true)) {
                    this.ExternalNameField = value;
                    this.RaisePropertyChanged("ExternalName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortName {
            get {
                return this.ShortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortNameField, value) != true)) {
                    this.ShortNameField = value;
                    this.RaisePropertyChanged("ShortName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RMService.IReleaseData")]
    public interface IReleaseData {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReleaseData/GetActiveReleaseIds", ReplyAction="http://tempuri.org/IReleaseData/GetActiveReleaseIdsResponse")]
        int[] GetActiveReleaseIds();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReleaseData/GetActiveReleases", ReplyAction="http://tempuri.org/IReleaseData/GetActiveReleasesResponse")]
        RMIntegration.RMService.Release[] GetActiveReleases();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReleaseData/GetRelease", ReplyAction="http://tempuri.org/IReleaseData/GetReleaseResponse")]
        RMIntegration.RMService.Release GetRelease(int releaseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReleaseData/GetWorkItemIdsById", ReplyAction="http://tempuri.org/IReleaseData/GetWorkItemIdsByIdResponse")]
        int[] GetWorkItemIdsById(int workItemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReleaseData/GetPatchById", ReplyAction="http://tempuri.org/IReleaseData/GetPatchByIdResponse")]
        RMIntegration.RMService.Patch GetPatchById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReleaseData/GetPatchFilesById", ReplyAction="http://tempuri.org/IReleaseData/GetPatchFilesByIdResponse")]
        RMIntegration.RMService.File[] GetPatchFilesById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReleaseData/GetReleaseIdsForPreMTP", ReplyAction="http://tempuri.org/IReleaseData/GetReleaseIdsForPreMTPResponse")]
        int[] GetReleaseIdsForPreMTP(string preMTPId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReleaseData/GetReleasesForPreMTP", ReplyAction="http://tempuri.org/IReleaseData/GetReleasesForPreMTPResponse")]
        RMIntegration.RMService.Release[] GetReleasesForPreMTP(string preMTPId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReleaseData/GetReleaseIdsForMTP", ReplyAction="http://tempuri.org/IReleaseData/GetReleaseIdsForMTPResponse")]
        int[] GetReleaseIdsForMTP(string mtpId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReleaseData/GetReleasesForMTP", ReplyAction="http://tempuri.org/IReleaseData/GetReleasesForMTPResponse")]
        RMIntegration.RMService.Release[] GetReleasesForMTP(string mtpId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReleaseData/GetBranchesForPatch", ReplyAction="http://tempuri.org/IReleaseData/GetBranchesForPatchResponse")]
        RMIntegration.RMService.Branch[] GetBranchesForPatch(int patchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReleaseData/GetBaseBuildNumberById", ReplyAction="http://tempuri.org/IReleaseData/GetBaseBuildNumberByIdResponse")]
        string GetBaseBuildNumberById(int workItemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReleaseData/GetComponentVersionById", ReplyAction="http://tempuri.org/IReleaseData/GetComponentVersionByIdResponse")]
        string GetComponentVersionById(int workItemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReleaseData/GetCustom1DataById", ReplyAction="http://tempuri.org/IReleaseData/GetCustom1DataByIdResponse")]
        string GetCustom1DataById(int workItemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReleaseData/GetLCUKBNumberById", ReplyAction="http://tempuri.org/IReleaseData/GetLCUKBNumberByIdResponse")]
        int GetLCUKBNumberById(int workItemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReleaseData/GetFixInfoByBugId", ReplyAction="http://tempuri.org/IReleaseData/GetFixInfoByBugIdResponse")]
        string GetFixInfoByBugId(int DevDivVSOBugId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReleaseData/GetPatchesByBugId", ReplyAction="http://tempuri.org/IReleaseData/GetPatchesByBugIdResponse")]
        RMIntegration.RMService.Patch[] GetPatchesByBugId(int DevDivVSOBugId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReleaseData/UpdateSymbolValidationResults", ReplyAction="http://tempuri.org/IReleaseData/UpdateSymbolValidationResultsResponse")]
        bool UpdateSymbolValidationResults(int workItemId, bool result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReleaseDataChannel : RMIntegration.RMService.IReleaseData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReleaseDataClient : System.ServiceModel.ClientBase<RMIntegration.RMService.IReleaseData>, RMIntegration.RMService.IReleaseData {
        
        public ReleaseDataClient() {
        }
        
        public ReleaseDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReleaseDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReleaseDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReleaseDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int[] GetActiveReleaseIds() {
            return base.Channel.GetActiveReleaseIds();
        }
        
        public RMIntegration.RMService.Release[] GetActiveReleases() {
            return base.Channel.GetActiveReleases();
        }
        
        public RMIntegration.RMService.Release GetRelease(int releaseId) {
            return base.Channel.GetRelease(releaseId);
        }
        
        public int[] GetWorkItemIdsById(int workItemId) {
            return base.Channel.GetWorkItemIdsById(workItemId);
        }
        
        public RMIntegration.RMService.Patch GetPatchById(int id) {
            return base.Channel.GetPatchById(id);
        }
        
        public RMIntegration.RMService.File[] GetPatchFilesById(int id) {
            return base.Channel.GetPatchFilesById(id);
        }
        
        public int[] GetReleaseIdsForPreMTP(string preMTPId) {
            return base.Channel.GetReleaseIdsForPreMTP(preMTPId);
        }
        
        public RMIntegration.RMService.Release[] GetReleasesForPreMTP(string preMTPId) {
            return base.Channel.GetReleasesForPreMTP(preMTPId);
        }
        
        public int[] GetReleaseIdsForMTP(string mtpId) {
            return base.Channel.GetReleaseIdsForMTP(mtpId);
        }
        
        public RMIntegration.RMService.Release[] GetReleasesForMTP(string mtpId) {
            return base.Channel.GetReleasesForMTP(mtpId);
        }
        
        public RMIntegration.RMService.Branch[] GetBranchesForPatch(int patchId) {
            return base.Channel.GetBranchesForPatch(patchId);
        }
        
        public string GetBaseBuildNumberById(int workItemId) {
            return base.Channel.GetBaseBuildNumberById(workItemId);
        }
        
        public string GetComponentVersionById(int workItemId) {
            return base.Channel.GetComponentVersionById(workItemId);
        }
        
        public string GetCustom1DataById(int workItemId) {
            return base.Channel.GetCustom1DataById(workItemId);
        }
        
        public int GetLCUKBNumberById(int workItemId) {
            return base.Channel.GetLCUKBNumberById(workItemId);
        }
        
        public string GetFixInfoByBugId(int DevDivVSOBugId) {
            return base.Channel.GetFixInfoByBugId(DevDivVSOBugId);
        }
        
        public RMIntegration.RMService.Patch[] GetPatchesByBugId(int DevDivVSOBugId) {
            return base.Channel.GetPatchesByBugId(DevDivVSOBugId);
        }
        
        public bool UpdateSymbolValidationResults(int workItemId, bool result) {
            return base.Channel.UpdateSymbolValidationResults(workItemId, result);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RMService.IConfiguration")]
    public interface IConfiguration {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/GetAllBranches", ReplyAction="http://tempuri.org/IConfiguration/GetAllBranchesResponse")]
        RMIntegration.RMService.Branch[] GetAllBranches();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/GetAllReleaseTypes", ReplyAction="http://tempuri.org/IConfiguration/GetAllReleaseTypesResponse")]
        RMIntegration.RMService.ReleaseType[] GetAllReleaseTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/GetAllProducts", ReplyAction="http://tempuri.org/IConfiguration/GetAllProductsResponse")]
        RMIntegration.RMService.Product[] GetAllProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/GetAllOS", ReplyAction="http://tempuri.org/IConfiguration/GetAllOSResponse")]
        RMIntegration.RMService.OS[] GetAllOS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/GetBranches", ReplyAction="http://tempuri.org/IConfiguration/GetBranchesResponse")]
        RMIntegration.RMService.Branch[] GetBranches(string[] releaseTypes, string[] productNames, string[] osNames);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConfigurationChannel : RMIntegration.RMService.IConfiguration, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConfigurationClient : System.ServiceModel.ClientBase<RMIntegration.RMService.IConfiguration>, RMIntegration.RMService.IConfiguration {
        
        public ConfigurationClient() {
        }
        
        public ConfigurationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConfigurationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigurationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigurationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RMIntegration.RMService.Branch[] GetAllBranches() {
            return base.Channel.GetAllBranches();
        }
        
        public RMIntegration.RMService.ReleaseType[] GetAllReleaseTypes() {
            return base.Channel.GetAllReleaseTypes();
        }
        
        public RMIntegration.RMService.Product[] GetAllProducts() {
            return base.Channel.GetAllProducts();
        }
        
        public RMIntegration.RMService.OS[] GetAllOS() {
            return base.Channel.GetAllOS();
        }
        
        public RMIntegration.RMService.Branch[] GetBranches(string[] releaseTypes, string[] productNames, string[] osNames) {
            return base.Channel.GetBranches(releaseTypes, productNames, osNames);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RMService.IReleaseManTask")]
    public interface IReleaseManTask {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReleaseManTask/RefreshPackageInformationFromTFS", ReplyAction="http://tempuri.org/IReleaseManTask/RefreshPackageInformationFromTFSResponse")]
        bool RefreshPackageInformationFromTFS(int releaseId, int patchId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReleaseManTaskChannel : RMIntegration.RMService.IReleaseManTask, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReleaseManTaskClient : System.ServiceModel.ClientBase<RMIntegration.RMService.IReleaseManTask>, RMIntegration.RMService.IReleaseManTask {
        
        public ReleaseManTaskClient() {
        }
        
        public ReleaseManTaskClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReleaseManTaskClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReleaseManTaskClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReleaseManTaskClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RefreshPackageInformationFromTFS(int releaseId, int patchId) {
            return base.Channel.RefreshPackageInformationFromTFS(releaseId, patchId);
        }
    }
}
