//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace THTestLib.GoFxService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GoFxServiceSoap", Namespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/")]
    public partial class GoFxService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TestEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateBuildRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPackageInfoByKbNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPackageInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWindowsReleaseTicketIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetKBNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCheckinInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBugChangelistCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReleaseTicketIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReleaseBranchesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBuildStampForReleaseTicketOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBuildInfoForReleaseTicketOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPackageRequestStateByBugIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPackageRequestStateByKBNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBranchForReleaseTicketOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTitleFromWIOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWorkItemTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetParametersFromWIOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListFieldsFromWIOperationCompleted;
        
        private System.Threading.SendOrPostCallback WorkItemExistsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetParameterFromWIOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetParameterOnWIOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddAttachmentToWIOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddHyperlinkToWIOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAttachmentUrlFromWIOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetParametersOnWIOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateVSOWorkItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFunctionalTestingTaskIdsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GoFxService() {
            this.Url = global::THTestLib.Properties.Settings.Default.THTestLib_GoFxService_GoFxService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TestEmailCompletedEventHandler TestEmailCompleted;
        
        /// <remarks/>
        public event CreateBuildRequestCompletedEventHandler CreateBuildRequestCompleted;
        
        /// <remarks/>
        public event GetPackageInfoByKbNumberCompletedEventHandler GetPackageInfoByKbNumberCompleted;
        
        /// <remarks/>
        public event GetPackageInfoCompletedEventHandler GetPackageInfoCompleted;
        
        /// <remarks/>
        public event GetWindowsReleaseTicketIdCompletedEventHandler GetWindowsReleaseTicketIdCompleted;
        
        /// <remarks/>
        public event GetKBNumberCompletedEventHandler GetKBNumberCompleted;
        
        /// <remarks/>
        public event GetCheckinInfoCompletedEventHandler GetCheckinInfoCompleted;
        
        /// <remarks/>
        public event GetBugChangelistCountCompletedEventHandler GetBugChangelistCountCompleted;
        
        /// <remarks/>
        public event GetReleaseTicketIdCompletedEventHandler GetReleaseTicketIdCompleted;
        
        /// <remarks/>
        public event GetReleaseBranchesCompletedEventHandler GetReleaseBranchesCompleted;
        
        /// <remarks/>
        public event GetBuildStampForReleaseTicketCompletedEventHandler GetBuildStampForReleaseTicketCompleted;
        
        /// <remarks/>
        public event GetBuildInfoForReleaseTicketCompletedEventHandler GetBuildInfoForReleaseTicketCompleted;
        
        /// <remarks/>
        public event GetPackageRequestStateByBugIdCompletedEventHandler GetPackageRequestStateByBugIdCompleted;
        
        /// <remarks/>
        public event GetPackageRequestStateByKBNumberCompletedEventHandler GetPackageRequestStateByKBNumberCompleted;
        
        /// <remarks/>
        public event GetBranchForReleaseTicketCompletedEventHandler GetBranchForReleaseTicketCompleted;
        
        /// <remarks/>
        public event GetTitleFromWICompletedEventHandler GetTitleFromWICompleted;
        
        /// <remarks/>
        public event GetWorkItemTypeCompletedEventHandler GetWorkItemTypeCompleted;
        
        /// <remarks/>
        public event GetParametersFromWICompletedEventHandler GetParametersFromWICompleted;
        
        /// <remarks/>
        public event ListFieldsFromWICompletedEventHandler ListFieldsFromWICompleted;
        
        /// <remarks/>
        public event WorkItemExistsCompletedEventHandler WorkItemExistsCompleted;
        
        /// <remarks/>
        public event GetParameterFromWICompletedEventHandler GetParameterFromWICompleted;
        
        /// <remarks/>
        public event SetParameterOnWICompletedEventHandler SetParameterOnWICompleted;
        
        /// <remarks/>
        public event AddAttachmentToWICompletedEventHandler AddAttachmentToWICompleted;
        
        /// <remarks/>
        public event AddHyperlinkToWICompletedEventHandler AddHyperlinkToWICompleted;
        
        /// <remarks/>
        public event GetAttachmentUrlFromWICompletedEventHandler GetAttachmentUrlFromWICompleted;
        
        /// <remarks/>
        public event SetParametersOnWICompletedEventHandler SetParametersOnWICompleted;
        
        /// <remarks/>
        public event CreateVSOWorkItemCompletedEventHandler CreateVSOWorkItemCompleted;
        
        /// <remarks/>
        public event GetFunctionalTestingTaskIdsCompletedEventHandler GetFunctionalTestingTaskIdsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ddse.redmond.corp.microsoft.com/GoFxServicing/TestEmail", RequestNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", ResponseNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool TestEmail() {
            object[] results = this.Invoke("TestEmail", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void TestEmailAsync() {
            this.TestEmailAsync(null);
        }
        
        /// <remarks/>
        public void TestEmailAsync(object userState) {
            if ((this.TestEmailOperationCompleted == null)) {
                this.TestEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestEmailOperationCompleted);
            }
            this.InvokeAsync("TestEmail", new object[0], this.TestEmailOperationCompleted, userState);
        }
        
        private void OnTestEmailOperationCompleted(object arg) {
            if ((this.TestEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestEmailCompleted(this, new TestEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ddse.redmond.corp.microsoft.com/GoFxServicing/CreateBuildRequest", RequestNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", ResponseNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CreateBuildRequest(int WorkItemId) {
            object[] results = this.Invoke("CreateBuildRequest", new object[] {
                        WorkItemId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CreateBuildRequestAsync(int WorkItemId) {
            this.CreateBuildRequestAsync(WorkItemId, null);
        }
        
        /// <remarks/>
        public void CreateBuildRequestAsync(int WorkItemId, object userState) {
            if ((this.CreateBuildRequestOperationCompleted == null)) {
                this.CreateBuildRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateBuildRequestOperationCompleted);
            }
            this.InvokeAsync("CreateBuildRequest", new object[] {
                        WorkItemId}, this.CreateBuildRequestOperationCompleted, userState);
        }
        
        private void OnCreateBuildRequestOperationCompleted(object arg) {
            if ((this.CreateBuildRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateBuildRequestCompleted(this, new CreateBuildRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ddse.redmond.corp.microsoft.com/GoFxServicing/GetPackageInfoByKbNumber", RequestNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", ResponseNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetPackageInfoByKbNumber(int KbArticle) {
            object[] results = this.Invoke("GetPackageInfoByKbNumber", new object[] {
                        KbArticle});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPackageInfoByKbNumberAsync(int KbArticle) {
            this.GetPackageInfoByKbNumberAsync(KbArticle, null);
        }
        
        /// <remarks/>
        public void GetPackageInfoByKbNumberAsync(int KbArticle, object userState) {
            if ((this.GetPackageInfoByKbNumberOperationCompleted == null)) {
                this.GetPackageInfoByKbNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPackageInfoByKbNumberOperationCompleted);
            }
            this.InvokeAsync("GetPackageInfoByKbNumber", new object[] {
                        KbArticle}, this.GetPackageInfoByKbNumberOperationCompleted, userState);
        }
        
        private void OnGetPackageInfoByKbNumberOperationCompleted(object arg) {
            if ((this.GetPackageInfoByKbNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPackageInfoByKbNumberCompleted(this, new GetPackageInfoByKbNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ddse.redmond.corp.microsoft.com/GoFxServicing/GetPackageInfo", RequestNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", ResponseNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetPackageInfo(int WSDBugId, bool IsNetOnly) {
            object[] results = this.Invoke("GetPackageInfo", new object[] {
                        WSDBugId,
                        IsNetOnly});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPackageInfoAsync(int WSDBugId, bool IsNetOnly) {
            this.GetPackageInfoAsync(WSDBugId, IsNetOnly, null);
        }
        
        /// <remarks/>
        public void GetPackageInfoAsync(int WSDBugId, bool IsNetOnly, object userState) {
            if ((this.GetPackageInfoOperationCompleted == null)) {
                this.GetPackageInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPackageInfoOperationCompleted);
            }
            this.InvokeAsync("GetPackageInfo", new object[] {
                        WSDBugId,
                        IsNetOnly}, this.GetPackageInfoOperationCompleted, userState);
        }
        
        private void OnGetPackageInfoOperationCompleted(object arg) {
            if ((this.GetPackageInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPackageInfoCompleted(this, new GetPackageInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ddse.redmond.corp.microsoft.com/GoFxServicing/GetWindowsReleaseTicketId", RequestNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", ResponseNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetWindowsReleaseTicketId(int WSDBugId) {
            object[] results = this.Invoke("GetWindowsReleaseTicketId", new object[] {
                        WSDBugId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetWindowsReleaseTicketIdAsync(int WSDBugId) {
            this.GetWindowsReleaseTicketIdAsync(WSDBugId, null);
        }
        
        /// <remarks/>
        public void GetWindowsReleaseTicketIdAsync(int WSDBugId, object userState) {
            if ((this.GetWindowsReleaseTicketIdOperationCompleted == null)) {
                this.GetWindowsReleaseTicketIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWindowsReleaseTicketIdOperationCompleted);
            }
            this.InvokeAsync("GetWindowsReleaseTicketId", new object[] {
                        WSDBugId}, this.GetWindowsReleaseTicketIdOperationCompleted, userState);
        }
        
        private void OnGetWindowsReleaseTicketIdOperationCompleted(object arg) {
            if ((this.GetWindowsReleaseTicketIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWindowsReleaseTicketIdCompleted(this, new GetWindowsReleaseTicketIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ddse.redmond.corp.microsoft.com/GoFxServicing/GetKBNumber", RequestNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", ResponseNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetKBNumber(string release, string OS) {
            object[] results = this.Invoke("GetKBNumber", new object[] {
                        release,
                        OS});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetKBNumberAsync(string release, string OS) {
            this.GetKBNumberAsync(release, OS, null);
        }
        
        /// <remarks/>
        public void GetKBNumberAsync(string release, string OS, object userState) {
            if ((this.GetKBNumberOperationCompleted == null)) {
                this.GetKBNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetKBNumberOperationCompleted);
            }
            this.InvokeAsync("GetKBNumber", new object[] {
                        release,
                        OS}, this.GetKBNumberOperationCompleted, userState);
        }
        
        private void OnGetKBNumberOperationCompleted(object arg) {
            if ((this.GetKBNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetKBNumberCompleted(this, new GetKBNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ddse.redmond.corp.microsoft.com/GoFxServicing/GetCheckinInfo", RequestNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", ResponseNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetCheckinInfo(int WSDBugId) {
            object[] results = this.Invoke("GetCheckinInfo", new object[] {
                        WSDBugId});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCheckinInfoAsync(int WSDBugId) {
            this.GetCheckinInfoAsync(WSDBugId, null);
        }
        
        /// <remarks/>
        public void GetCheckinInfoAsync(int WSDBugId, object userState) {
            if ((this.GetCheckinInfoOperationCompleted == null)) {
                this.GetCheckinInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCheckinInfoOperationCompleted);
            }
            this.InvokeAsync("GetCheckinInfo", new object[] {
                        WSDBugId}, this.GetCheckinInfoOperationCompleted, userState);
        }
        
        private void OnGetCheckinInfoOperationCompleted(object arg) {
            if ((this.GetCheckinInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCheckinInfoCompleted(this, new GetCheckinInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ddse.redmond.corp.microsoft.com/GoFxServicing/GetBugChangelistCount", RequestNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", ResponseNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetBugChangelistCount(int WSDBugId) {
            object[] results = this.Invoke("GetBugChangelistCount", new object[] {
                        WSDBugId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetBugChangelistCountAsync(int WSDBugId) {
            this.GetBugChangelistCountAsync(WSDBugId, null);
        }
        
        /// <remarks/>
        public void GetBugChangelistCountAsync(int WSDBugId, object userState) {
            if ((this.GetBugChangelistCountOperationCompleted == null)) {
                this.GetBugChangelistCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBugChangelistCountOperationCompleted);
            }
            this.InvokeAsync("GetBugChangelistCount", new object[] {
                        WSDBugId}, this.GetBugChangelistCountOperationCompleted, userState);
        }
        
        private void OnGetBugChangelistCountOperationCompleted(object arg) {
            if ((this.GetBugChangelistCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBugChangelistCountCompleted(this, new GetBugChangelistCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ddse.redmond.corp.microsoft.com/GoFxServicing/GetReleaseTicketId", RequestNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", ResponseNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetReleaseTicketId(string release, string OS, bool IsSecRelease) {
            object[] results = this.Invoke("GetReleaseTicketId", new object[] {
                        release,
                        OS,
                        IsSecRelease});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetReleaseTicketIdAsync(string release, string OS, bool IsSecRelease) {
            this.GetReleaseTicketIdAsync(release, OS, IsSecRelease, null);
        }
        
        /// <remarks/>
        public void GetReleaseTicketIdAsync(string release, string OS, bool IsSecRelease, object userState) {
            if ((this.GetReleaseTicketIdOperationCompleted == null)) {
                this.GetReleaseTicketIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReleaseTicketIdOperationCompleted);
            }
            this.InvokeAsync("GetReleaseTicketId", new object[] {
                        release,
                        OS,
                        IsSecRelease}, this.GetReleaseTicketIdOperationCompleted, userState);
        }
        
        private void OnGetReleaseTicketIdOperationCompleted(object arg) {
            if ((this.GetReleaseTicketIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReleaseTicketIdCompleted(this, new GetReleaseTicketIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ddse.redmond.corp.microsoft.com/GoFxServicing/GetReleaseBranches", RequestNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", ResponseNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetReleaseBranches(string release, bool IsSecRelease) {
            object[] results = this.Invoke("GetReleaseBranches", new object[] {
                        release,
                        IsSecRelease});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetReleaseBranchesAsync(string release, bool IsSecRelease) {
            this.GetReleaseBranchesAsync(release, IsSecRelease, null);
        }
        
        /// <remarks/>
        public void GetReleaseBranchesAsync(string release, bool IsSecRelease, object userState) {
            if ((this.GetReleaseBranchesOperationCompleted == null)) {
                this.GetReleaseBranchesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReleaseBranchesOperationCompleted);
            }
            this.InvokeAsync("GetReleaseBranches", new object[] {
                        release,
                        IsSecRelease}, this.GetReleaseBranchesOperationCompleted, userState);
        }
        
        private void OnGetReleaseBranchesOperationCompleted(object arg) {
            if ((this.GetReleaseBranchesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReleaseBranchesCompleted(this, new GetReleaseBranchesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ddse.redmond.corp.microsoft.com/GoFxServicing/GetBuildStampForReleaseTick" +
            "et", RequestNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", ResponseNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime GetBuildStampForReleaseTicket(int releaseTicketId) {
            object[] results = this.Invoke("GetBuildStampForReleaseTicket", new object[] {
                        releaseTicketId});
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void GetBuildStampForReleaseTicketAsync(int releaseTicketId) {
            this.GetBuildStampForReleaseTicketAsync(releaseTicketId, null);
        }
        
        /// <remarks/>
        public void GetBuildStampForReleaseTicketAsync(int releaseTicketId, object userState) {
            if ((this.GetBuildStampForReleaseTicketOperationCompleted == null)) {
                this.GetBuildStampForReleaseTicketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBuildStampForReleaseTicketOperationCompleted);
            }
            this.InvokeAsync("GetBuildStampForReleaseTicket", new object[] {
                        releaseTicketId}, this.GetBuildStampForReleaseTicketOperationCompleted, userState);
        }
        
        private void OnGetBuildStampForReleaseTicketOperationCompleted(object arg) {
            if ((this.GetBuildStampForReleaseTicketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBuildStampForReleaseTicketCompleted(this, new GetBuildStampForReleaseTicketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ddse.redmond.corp.microsoft.com/GoFxServicing/GetBuildInfoForReleaseTicke" +
            "t", RequestNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", ResponseNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetBuildInfoForReleaseTicket(int releaseTicketId) {
            object[] results = this.Invoke("GetBuildInfoForReleaseTicket", new object[] {
                        releaseTicketId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetBuildInfoForReleaseTicketAsync(int releaseTicketId) {
            this.GetBuildInfoForReleaseTicketAsync(releaseTicketId, null);
        }
        
        /// <remarks/>
        public void GetBuildInfoForReleaseTicketAsync(int releaseTicketId, object userState) {
            if ((this.GetBuildInfoForReleaseTicketOperationCompleted == null)) {
                this.GetBuildInfoForReleaseTicketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBuildInfoForReleaseTicketOperationCompleted);
            }
            this.InvokeAsync("GetBuildInfoForReleaseTicket", new object[] {
                        releaseTicketId}, this.GetBuildInfoForReleaseTicketOperationCompleted, userState);
        }
        
        private void OnGetBuildInfoForReleaseTicketOperationCompleted(object arg) {
            if ((this.GetBuildInfoForReleaseTicketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBuildInfoForReleaseTicketCompleted(this, new GetBuildInfoForReleaseTicketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ddse.redmond.corp.microsoft.com/GoFxServicing/GetPackageRequestStateByBug" +
            "Id", RequestNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", ResponseNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPackageRequestStateByBugId(int packageBugId) {
            object[] results = this.Invoke("GetPackageRequestStateByBugId", new object[] {
                        packageBugId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPackageRequestStateByBugIdAsync(int packageBugId) {
            this.GetPackageRequestStateByBugIdAsync(packageBugId, null);
        }
        
        /// <remarks/>
        public void GetPackageRequestStateByBugIdAsync(int packageBugId, object userState) {
            if ((this.GetPackageRequestStateByBugIdOperationCompleted == null)) {
                this.GetPackageRequestStateByBugIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPackageRequestStateByBugIdOperationCompleted);
            }
            this.InvokeAsync("GetPackageRequestStateByBugId", new object[] {
                        packageBugId}, this.GetPackageRequestStateByBugIdOperationCompleted, userState);
        }
        
        private void OnGetPackageRequestStateByBugIdOperationCompleted(object arg) {
            if ((this.GetPackageRequestStateByBugIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPackageRequestStateByBugIdCompleted(this, new GetPackageRequestStateByBugIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ddse.redmond.corp.microsoft.com/GoFxServicing/GetPackageRequestStateByKBN" +
            "umber", RequestNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", ResponseNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPackageRequestStateByKBNumber(int kbNumber) {
            object[] results = this.Invoke("GetPackageRequestStateByKBNumber", new object[] {
                        kbNumber});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPackageRequestStateByKBNumberAsync(int kbNumber) {
            this.GetPackageRequestStateByKBNumberAsync(kbNumber, null);
        }
        
        /// <remarks/>
        public void GetPackageRequestStateByKBNumberAsync(int kbNumber, object userState) {
            if ((this.GetPackageRequestStateByKBNumberOperationCompleted == null)) {
                this.GetPackageRequestStateByKBNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPackageRequestStateByKBNumberOperationCompleted);
            }
            this.InvokeAsync("GetPackageRequestStateByKBNumber", new object[] {
                        kbNumber}, this.GetPackageRequestStateByKBNumberOperationCompleted, userState);
        }
        
        private void OnGetPackageRequestStateByKBNumberOperationCompleted(object arg) {
            if ((this.GetPackageRequestStateByKBNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPackageRequestStateByKBNumberCompleted(this, new GetPackageRequestStateByKBNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ddse.redmond.corp.microsoft.com/GoFxServicing/GetBranchForReleaseTicket", RequestNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", ResponseNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetBranchForReleaseTicket(int releaseTicketId) {
            object[] results = this.Invoke("GetBranchForReleaseTicket", new object[] {
                        releaseTicketId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetBranchForReleaseTicketAsync(int releaseTicketId) {
            this.GetBranchForReleaseTicketAsync(releaseTicketId, null);
        }
        
        /// <remarks/>
        public void GetBranchForReleaseTicketAsync(int releaseTicketId, object userState) {
            if ((this.GetBranchForReleaseTicketOperationCompleted == null)) {
                this.GetBranchForReleaseTicketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBranchForReleaseTicketOperationCompleted);
            }
            this.InvokeAsync("GetBranchForReleaseTicket", new object[] {
                        releaseTicketId}, this.GetBranchForReleaseTicketOperationCompleted, userState);
        }
        
        private void OnGetBranchForReleaseTicketOperationCompleted(object arg) {
            if ((this.GetBranchForReleaseTicketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBranchForReleaseTicketCompleted(this, new GetBranchForReleaseTicketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ddse.redmond.corp.microsoft.com/GoFxServicing/GetTitleFromWI", RequestNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", ResponseNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTitleFromWI(int workItemId, TFSProject project) {
            object[] results = this.Invoke("GetTitleFromWI", new object[] {
                        workItemId,
                        project});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTitleFromWIAsync(int workItemId, TFSProject project) {
            this.GetTitleFromWIAsync(workItemId, project, null);
        }
        
        /// <remarks/>
        public void GetTitleFromWIAsync(int workItemId, TFSProject project, object userState) {
            if ((this.GetTitleFromWIOperationCompleted == null)) {
                this.GetTitleFromWIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTitleFromWIOperationCompleted);
            }
            this.InvokeAsync("GetTitleFromWI", new object[] {
                        workItemId,
                        project}, this.GetTitleFromWIOperationCompleted, userState);
        }
        
        private void OnGetTitleFromWIOperationCompleted(object arg) {
            if ((this.GetTitleFromWICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTitleFromWICompleted(this, new GetTitleFromWICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ddse.redmond.corp.microsoft.com/GoFxServicing/GetWorkItemType", RequestNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", ResponseNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetWorkItemType(int workItemId, TFSProject project) {
            object[] results = this.Invoke("GetWorkItemType", new object[] {
                        workItemId,
                        project});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetWorkItemTypeAsync(int workItemId, TFSProject project) {
            this.GetWorkItemTypeAsync(workItemId, project, null);
        }
        
        /// <remarks/>
        public void GetWorkItemTypeAsync(int workItemId, TFSProject project, object userState) {
            if ((this.GetWorkItemTypeOperationCompleted == null)) {
                this.GetWorkItemTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWorkItemTypeOperationCompleted);
            }
            this.InvokeAsync("GetWorkItemType", new object[] {
                        workItemId,
                        project}, this.GetWorkItemTypeOperationCompleted, userState);
        }
        
        private void OnGetWorkItemTypeOperationCompleted(object arg) {
            if ((this.GetWorkItemTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWorkItemTypeCompleted(this, new GetWorkItemTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ddse.redmond.corp.microsoft.com/GoFxServicing/GetParametersFromWI", RequestNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", ResponseNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetParametersFromWI(int workItemId, TFSProject project) {
            object[] results = this.Invoke("GetParametersFromWI", new object[] {
                        workItemId,
                        project});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetParametersFromWIAsync(int workItemId, TFSProject project) {
            this.GetParametersFromWIAsync(workItemId, project, null);
        }
        
        /// <remarks/>
        public void GetParametersFromWIAsync(int workItemId, TFSProject project, object userState) {
            if ((this.GetParametersFromWIOperationCompleted == null)) {
                this.GetParametersFromWIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetParametersFromWIOperationCompleted);
            }
            this.InvokeAsync("GetParametersFromWI", new object[] {
                        workItemId,
                        project}, this.GetParametersFromWIOperationCompleted, userState);
        }
        
        private void OnGetParametersFromWIOperationCompleted(object arg) {
            if ((this.GetParametersFromWICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetParametersFromWICompleted(this, new GetParametersFromWICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ddse.redmond.corp.microsoft.com/GoFxServicing/ListFieldsFromWI", RequestNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", ResponseNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ListFieldsFromWI(int workItemId, TFSProject project) {
            object[] results = this.Invoke("ListFieldsFromWI", new object[] {
                        workItemId,
                        project});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ListFieldsFromWIAsync(int workItemId, TFSProject project) {
            this.ListFieldsFromWIAsync(workItemId, project, null);
        }
        
        /// <remarks/>
        public void ListFieldsFromWIAsync(int workItemId, TFSProject project, object userState) {
            if ((this.ListFieldsFromWIOperationCompleted == null)) {
                this.ListFieldsFromWIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListFieldsFromWIOperationCompleted);
            }
            this.InvokeAsync("ListFieldsFromWI", new object[] {
                        workItemId,
                        project}, this.ListFieldsFromWIOperationCompleted, userState);
        }
        
        private void OnListFieldsFromWIOperationCompleted(object arg) {
            if ((this.ListFieldsFromWICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListFieldsFromWICompleted(this, new ListFieldsFromWICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ddse.redmond.corp.microsoft.com/GoFxServicing/WorkItemExists", RequestNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", ResponseNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool WorkItemExists(int workItemId, TFSProject project) {
            object[] results = this.Invoke("WorkItemExists", new object[] {
                        workItemId,
                        project});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void WorkItemExistsAsync(int workItemId, TFSProject project) {
            this.WorkItemExistsAsync(workItemId, project, null);
        }
        
        /// <remarks/>
        public void WorkItemExistsAsync(int workItemId, TFSProject project, object userState) {
            if ((this.WorkItemExistsOperationCompleted == null)) {
                this.WorkItemExistsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWorkItemExistsOperationCompleted);
            }
            this.InvokeAsync("WorkItemExists", new object[] {
                        workItemId,
                        project}, this.WorkItemExistsOperationCompleted, userState);
        }
        
        private void OnWorkItemExistsOperationCompleted(object arg) {
            if ((this.WorkItemExistsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WorkItemExistsCompleted(this, new WorkItemExistsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ddse.redmond.corp.microsoft.com/GoFxServicing/GetParameterFromWI", RequestNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", ResponseNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetParameterFromWI(int workItemId, TFSProject project, string fieldName) {
            object[] results = this.Invoke("GetParameterFromWI", new object[] {
                        workItemId,
                        project,
                        fieldName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetParameterFromWIAsync(int workItemId, TFSProject project, string fieldName) {
            this.GetParameterFromWIAsync(workItemId, project, fieldName, null);
        }
        
        /// <remarks/>
        public void GetParameterFromWIAsync(int workItemId, TFSProject project, string fieldName, object userState) {
            if ((this.GetParameterFromWIOperationCompleted == null)) {
                this.GetParameterFromWIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetParameterFromWIOperationCompleted);
            }
            this.InvokeAsync("GetParameterFromWI", new object[] {
                        workItemId,
                        project,
                        fieldName}, this.GetParameterFromWIOperationCompleted, userState);
        }
        
        private void OnGetParameterFromWIOperationCompleted(object arg) {
            if ((this.GetParameterFromWICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetParameterFromWICompleted(this, new GetParameterFromWICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ddse.redmond.corp.microsoft.com/GoFxServicing/SetParameterOnWI", RequestNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", ResponseNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SetParameterOnWI(int workItemId, TFSProject project, string fieldName, string fieldValue) {
            object[] results = this.Invoke("SetParameterOnWI", new object[] {
                        workItemId,
                        project,
                        fieldName,
                        fieldValue});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SetParameterOnWIAsync(int workItemId, TFSProject project, string fieldName, string fieldValue) {
            this.SetParameterOnWIAsync(workItemId, project, fieldName, fieldValue, null);
        }
        
        /// <remarks/>
        public void SetParameterOnWIAsync(int workItemId, TFSProject project, string fieldName, string fieldValue, object userState) {
            if ((this.SetParameterOnWIOperationCompleted == null)) {
                this.SetParameterOnWIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetParameterOnWIOperationCompleted);
            }
            this.InvokeAsync("SetParameterOnWI", new object[] {
                        workItemId,
                        project,
                        fieldName,
                        fieldValue}, this.SetParameterOnWIOperationCompleted, userState);
        }
        
        private void OnSetParameterOnWIOperationCompleted(object arg) {
            if ((this.SetParameterOnWICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetParameterOnWICompleted(this, new SetParameterOnWICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ddse.redmond.corp.microsoft.com/GoFxServicing/AddAttachmentToWI", RequestNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", ResponseNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddAttachmentToWI(int workItemId, TFSProject project, string attachmentPath, string attachmentComment) {
            object[] results = this.Invoke("AddAttachmentToWI", new object[] {
                        workItemId,
                        project,
                        attachmentPath,
                        attachmentComment});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddAttachmentToWIAsync(int workItemId, TFSProject project, string attachmentPath, string attachmentComment) {
            this.AddAttachmentToWIAsync(workItemId, project, attachmentPath, attachmentComment, null);
        }
        
        /// <remarks/>
        public void AddAttachmentToWIAsync(int workItemId, TFSProject project, string attachmentPath, string attachmentComment, object userState) {
            if ((this.AddAttachmentToWIOperationCompleted == null)) {
                this.AddAttachmentToWIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddAttachmentToWIOperationCompleted);
            }
            this.InvokeAsync("AddAttachmentToWI", new object[] {
                        workItemId,
                        project,
                        attachmentPath,
                        attachmentComment}, this.AddAttachmentToWIOperationCompleted, userState);
        }
        
        private void OnAddAttachmentToWIOperationCompleted(object arg) {
            if ((this.AddAttachmentToWICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddAttachmentToWICompleted(this, new AddAttachmentToWICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ddse.redmond.corp.microsoft.com/GoFxServicing/AddHyperlinkToWI", RequestNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", ResponseNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddHyperlinkToWI(int workItemId, TFSProject project, string url, string comment) {
            object[] results = this.Invoke("AddHyperlinkToWI", new object[] {
                        workItemId,
                        project,
                        url,
                        comment});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddHyperlinkToWIAsync(int workItemId, TFSProject project, string url, string comment) {
            this.AddHyperlinkToWIAsync(workItemId, project, url, comment, null);
        }
        
        /// <remarks/>
        public void AddHyperlinkToWIAsync(int workItemId, TFSProject project, string url, string comment, object userState) {
            if ((this.AddHyperlinkToWIOperationCompleted == null)) {
                this.AddHyperlinkToWIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddHyperlinkToWIOperationCompleted);
            }
            this.InvokeAsync("AddHyperlinkToWI", new object[] {
                        workItemId,
                        project,
                        url,
                        comment}, this.AddHyperlinkToWIOperationCompleted, userState);
        }
        
        private void OnAddHyperlinkToWIOperationCompleted(object arg) {
            if ((this.AddHyperlinkToWICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddHyperlinkToWICompleted(this, new AddHyperlinkToWICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ddse.redmond.corp.microsoft.com/GoFxServicing/GetAttachmentUrlFromWI", RequestNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", ResponseNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAttachmentUrlFromWI(int workItemId, TFSProject project, string attachmentName, string attachmentComment) {
            object[] results = this.Invoke("GetAttachmentUrlFromWI", new object[] {
                        workItemId,
                        project,
                        attachmentName,
                        attachmentComment});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAttachmentUrlFromWIAsync(int workItemId, TFSProject project, string attachmentName, string attachmentComment) {
            this.GetAttachmentUrlFromWIAsync(workItemId, project, attachmentName, attachmentComment, null);
        }
        
        /// <remarks/>
        public void GetAttachmentUrlFromWIAsync(int workItemId, TFSProject project, string attachmentName, string attachmentComment, object userState) {
            if ((this.GetAttachmentUrlFromWIOperationCompleted == null)) {
                this.GetAttachmentUrlFromWIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAttachmentUrlFromWIOperationCompleted);
            }
            this.InvokeAsync("GetAttachmentUrlFromWI", new object[] {
                        workItemId,
                        project,
                        attachmentName,
                        attachmentComment}, this.GetAttachmentUrlFromWIOperationCompleted, userState);
        }
        
        private void OnGetAttachmentUrlFromWIOperationCompleted(object arg) {
            if ((this.GetAttachmentUrlFromWICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAttachmentUrlFromWICompleted(this, new GetAttachmentUrlFromWICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ddse.redmond.corp.microsoft.com/GoFxServicing/SetParametersOnWI", RequestNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", ResponseNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SetParametersOnWI(int workItemId, TFSProject project, string[] fields, string[] values) {
            object[] results = this.Invoke("SetParametersOnWI", new object[] {
                        workItemId,
                        project,
                        fields,
                        values});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SetParametersOnWIAsync(int workItemId, TFSProject project, string[] fields, string[] values) {
            this.SetParametersOnWIAsync(workItemId, project, fields, values, null);
        }
        
        /// <remarks/>
        public void SetParametersOnWIAsync(int workItemId, TFSProject project, string[] fields, string[] values, object userState) {
            if ((this.SetParametersOnWIOperationCompleted == null)) {
                this.SetParametersOnWIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetParametersOnWIOperationCompleted);
            }
            this.InvokeAsync("SetParametersOnWI", new object[] {
                        workItemId,
                        project,
                        fields,
                        values}, this.SetParametersOnWIOperationCompleted, userState);
        }
        
        private void OnSetParametersOnWIOperationCompleted(object arg) {
            if ((this.SetParametersOnWICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetParametersOnWICompleted(this, new SetParametersOnWICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ddse.redmond.corp.microsoft.com/GoFxServicing/CreateVSOWorkItem", RequestNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", ResponseNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] CreateVSOWorkItem(TFSProject project, string workItemXML) {
            object[] results = this.Invoke("CreateVSOWorkItem", new object[] {
                        project,
                        workItemXML});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateVSOWorkItemAsync(TFSProject project, string workItemXML) {
            this.CreateVSOWorkItemAsync(project, workItemXML, null);
        }
        
        /// <remarks/>
        public void CreateVSOWorkItemAsync(TFSProject project, string workItemXML, object userState) {
            if ((this.CreateVSOWorkItemOperationCompleted == null)) {
                this.CreateVSOWorkItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateVSOWorkItemOperationCompleted);
            }
            this.InvokeAsync("CreateVSOWorkItem", new object[] {
                        project,
                        workItemXML}, this.CreateVSOWorkItemOperationCompleted, userState);
        }
        
        private void OnCreateVSOWorkItemOperationCompleted(object arg) {
            if ((this.CreateVSOWorkItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateVSOWorkItemCompleted(this, new CreateVSOWorkItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ddse.redmond.corp.microsoft.com/GoFxServicing/GetFunctionalTestingTaskIds" +
            "", RequestNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", ResponseNamespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] GetFunctionalTestingTaskIds(int kbNumber, string mtp, string osToMatch) {
            object[] results = this.Invoke("GetFunctionalTestingTaskIds", new object[] {
                        kbNumber,
                        mtp,
                        osToMatch});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void GetFunctionalTestingTaskIdsAsync(int kbNumber, string mtp, string osToMatch) {
            this.GetFunctionalTestingTaskIdsAsync(kbNumber, mtp, osToMatch, null);
        }
        
        /// <remarks/>
        public void GetFunctionalTestingTaskIdsAsync(int kbNumber, string mtp, string osToMatch, object userState) {
            if ((this.GetFunctionalTestingTaskIdsOperationCompleted == null)) {
                this.GetFunctionalTestingTaskIdsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFunctionalTestingTaskIdsOperationCompleted);
            }
            this.InvokeAsync("GetFunctionalTestingTaskIds", new object[] {
                        kbNumber,
                        mtp,
                        osToMatch}, this.GetFunctionalTestingTaskIdsOperationCompleted, userState);
        }
        
        private void OnGetFunctionalTestingTaskIdsOperationCompleted(object arg) {
            if ((this.GetFunctionalTestingTaskIdsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFunctionalTestingTaskIdsCompleted(this, new GetFunctionalTestingTaskIdsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ddse.redmond.corp.microsoft.com/GoFxServicing/")]
    public enum TFSProject {
        
        /// <remarks/>
        DevDivServicing,
        
        /// <remarks/>
        DevDivVSO,
        
        /// <remarks/>
        MSFTVSO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void TestEmailCompletedEventHandler(object sender, TestEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CreateBuildRequestCompletedEventHandler(object sender, CreateBuildRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateBuildRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateBuildRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetPackageInfoByKbNumberCompletedEventHandler(object sender, GetPackageInfoByKbNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPackageInfoByKbNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPackageInfoByKbNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetPackageInfoCompletedEventHandler(object sender, GetPackageInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPackageInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPackageInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetWindowsReleaseTicketIdCompletedEventHandler(object sender, GetWindowsReleaseTicketIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWindowsReleaseTicketIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWindowsReleaseTicketIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetKBNumberCompletedEventHandler(object sender, GetKBNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetKBNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetKBNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetCheckinInfoCompletedEventHandler(object sender, GetCheckinInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCheckinInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCheckinInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetBugChangelistCountCompletedEventHandler(object sender, GetBugChangelistCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBugChangelistCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBugChangelistCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetReleaseTicketIdCompletedEventHandler(object sender, GetReleaseTicketIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReleaseTicketIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReleaseTicketIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetReleaseBranchesCompletedEventHandler(object sender, GetReleaseBranchesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReleaseBranchesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReleaseBranchesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetBuildStampForReleaseTicketCompletedEventHandler(object sender, GetBuildStampForReleaseTicketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBuildStampForReleaseTicketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBuildStampForReleaseTicketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetBuildInfoForReleaseTicketCompletedEventHandler(object sender, GetBuildInfoForReleaseTicketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBuildInfoForReleaseTicketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBuildInfoForReleaseTicketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetPackageRequestStateByBugIdCompletedEventHandler(object sender, GetPackageRequestStateByBugIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPackageRequestStateByBugIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPackageRequestStateByBugIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetPackageRequestStateByKBNumberCompletedEventHandler(object sender, GetPackageRequestStateByKBNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPackageRequestStateByKBNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPackageRequestStateByKBNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetBranchForReleaseTicketCompletedEventHandler(object sender, GetBranchForReleaseTicketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBranchForReleaseTicketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBranchForReleaseTicketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetTitleFromWICompletedEventHandler(object sender, GetTitleFromWICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTitleFromWICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTitleFromWICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetWorkItemTypeCompletedEventHandler(object sender, GetWorkItemTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWorkItemTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWorkItemTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetParametersFromWICompletedEventHandler(object sender, GetParametersFromWICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetParametersFromWICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetParametersFromWICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ListFieldsFromWICompletedEventHandler(object sender, ListFieldsFromWICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListFieldsFromWICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListFieldsFromWICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WorkItemExistsCompletedEventHandler(object sender, WorkItemExistsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WorkItemExistsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WorkItemExistsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetParameterFromWICompletedEventHandler(object sender, GetParameterFromWICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetParameterFromWICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetParameterFromWICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void SetParameterOnWICompletedEventHandler(object sender, SetParameterOnWICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetParameterOnWICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetParameterOnWICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void AddAttachmentToWICompletedEventHandler(object sender, AddAttachmentToWICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddAttachmentToWICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddAttachmentToWICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void AddHyperlinkToWICompletedEventHandler(object sender, AddHyperlinkToWICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddHyperlinkToWICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddHyperlinkToWICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetAttachmentUrlFromWICompletedEventHandler(object sender, GetAttachmentUrlFromWICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAttachmentUrlFromWICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAttachmentUrlFromWICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void SetParametersOnWICompletedEventHandler(object sender, SetParametersOnWICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetParametersOnWICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetParametersOnWICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CreateVSOWorkItemCompletedEventHandler(object sender, CreateVSOWorkItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateVSOWorkItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateVSOWorkItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetFunctionalTestingTaskIdsCompletedEventHandler(object sender, GetFunctionalTestingTaskIdsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFunctionalTestingTaskIdsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFunctionalTestingTaskIdsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591